version: '3.4'

name: garage

services:
  garage-web:
    image: ${DOCKER_REGISTRY-}garageweb
    container_name: garage-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Garage.Web/Garage.Web/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - garage-db
      - garage-seq 
    links: 
      - garage-db
      
  garage-db:
    image: postgres:latest
    container_name: garage-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=garage
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme 

  garage-db-admin:
    image: dpage/pgadmin4:latest
    container_name: garage-db-admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=changeme
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 15432:80
    depends_on:
      - garage-db

  garage-seq:
    image: datalust/seq:latest
    container_name: garage-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=QME91ifplvCXi0wkpaobjqEldl8NhQlOXJKSf5ttDfmHt/gHD1hLma/1hl51WL/0q5/4OhESZ0EEy1ecYRwv79Ciu8sQvNkpZ1ms78/E9q5f  #changeme
    ports:
      - 8090:80
      - 5341:5341