version: '3.4'

name: garage

services:
  garage-web:
    image: ${DOCKER_REGISTRY-}garageweb
    container_name: garage-web
    restart: unless-stopped
    build:
      context: .
      dockerfile: Garage.Web/Garage.Web/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - garage-db-identity
      - garage-db-app
    links:
      - garage-db-identity
      - garage-db-app

  garage-db-identity:
    image: postgres:latest
    container_name: garage-db-identity
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=garage_identity
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
    
  garage-db-app:
    image: postgres:latest
    container_name: garage-db-app
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=garage_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme

  garage-db-admin:
    image: dpage/pgadmin4:latest
    container_name: garage-db-admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.com
      - PGADMIN_DEFAULT_PASSWORD=changeme
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 15432:80
    depends_on:
      - garage-db-identity
      - garage-db-app