version: '3.4'

name: garage

services:
  garage-web:
    image: ${DOCKER_REGISTRY-}garageweb
    container_name: garage-web
    build:
      context: .
      dockerfile: Garage.Web/Garage.Web/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: unless-stopped

  garage-db-identity:
    image: postgres
    container_name: garage-db-identity
    ports:
      - "5432:5432"
    restart: unless-stopped
    
  garage-db-app:
    image: postgres
    container_name: garage-db-app
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=test
    restart: unless-stopped
